<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\\TruyenVerse.Domain\\TruyenVerse.Domain.csproj" />
    <ProjectReference Include="..\\TruyenVerse.Application\\TruyenVerse.Application.csproj" />
  </ItemGroup>
</Project>
